# Generated by Django 3.0.4 on 2020-03-24 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_name', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('image', models.ImageField(default='image/default.png', upload_to='image/%Y/%m')),
                ('type_idx', models.IntegerField()),
                ('type_idx2', models.IntegerField()),
                ('lower_evolve', models.ManyToManyField(blank=True, related_name='low', to='pokemon.Pokemon')),
                ('types', models.ManyToManyField(to='pokemon.Type')),
                ('upper_evolve', models.ManyToManyField(related_name='up', to='pokemon.Pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release', models.DateField(blank=True, null=True)),
                ('summary', models.TextField(max_length=1000)),
                ('number', models.IntegerField()),
                ('image', models.ImageField(upload_to='movies/%Y/%m')),
                ('pokemon', models.ManyToManyField(to='pokemon.Pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_name', models.CharField(max_length=30)),
                ('damage', models.DecimalField(decimal_places=0, max_digits=3)),
                ('types', models.ManyToManyField(to='pokemon.Type')),
            ],
        ),
    ]
