# Generated by Django 3.0.4 on 2020-03-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='evolve_tool',
            field=models.ImageField(blank=True, default='image/default.png', upload_to='image/%Y/%m'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='levelup',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemon',
            name='special_case',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='upper_evolve',
            field=models.ManyToManyField(blank=True, related_name='up', to='pokemon.Pokemon'),
        ),
    ]
