# Generated by Django 3.0.4 on 2020-03-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_auto_20200323_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='summary',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='weakness',
            field=models.ManyToManyField(related_name='weakness', to='pokemon.Type'),
        ),
    ]
