# Generated by Django 3.0.4 on 2020-03-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0005_auto_20200324_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='evolve_img',
            field=models.ImageField(blank=True, default='image/default.png', upload_to='image/evolve'),
        ),
    ]
