# Generated by Django 3.0.4 on 2020-03-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0006_pokemon_evolve_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='evolve_kinds',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
