# Generated by Django 3.0.4 on 2020-03-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0008_auto_20200325_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generation',
            name='gen',
        ),
        migrations.AddField(
            model_name='generation',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2),
        ),
    ]
