# Generated by Django 3.0.4 on 2020-03-25 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0010_auto_20200325_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pokemon.Region'),
            preserve_default=False,
        ),
    ]
