# Generated by Django 3.0.4 on 2020-03-25 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0013_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='generation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pokemon.Generation'),
            preserve_default=False,
        ),
    ]
