# Generated by Django 3.0.4 on 2020-03-26 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0014_pokemon_generation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type_idx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type1', to='pokemon.Type'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type_idx2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type2', to='pokemon.Type'),
        ),
    ]
