# Generated by Django 3.0.4 on 2020-03-26 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0015_auto_20200325_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='type_idx',
            new_name='type1',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='type_idx2',
            new_name='type2',
        ),
    ]
