# Generated by Django 3.0.4 on 2020-03-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0016_auto_20200326_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='type1',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='type2',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='type_idx',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemon',
            name='type_idx2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
