# Generated by Django 2.2.11 on 2020-03-31 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0017_auto_20200326_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(upload_to='movies'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='evolve_img',
            field=models.ImageField(blank=True, default='image/default.png', upload_to='evolve_images'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='evolve_tool',
            field=models.ImageField(blank=True, default='image/default.png', upload_to='evolve_tools'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(default='image/default.png', upload_to='profile_image'),
        ),
    ]
