# Generated by Django 2.2.11 on 2020-04-01 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0019_pokemon_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='url',
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='evolve_img',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='evolve_tool',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
