# Generated by Django 2.2.11 on 2020-04-01 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0020_auto_20200331_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='special_forms',
            field=models.ManyToManyField(related_name='special', to='pokemon.Special'),
        ),
    ]
