# Generated by Django 2.2.11 on 2020-04-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0022_auto_20200402_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='summary',
            field=models.TextField(max_length=2000),
        ),
    ]
