# Generated by Django 2.2.11 on 2020-04-14 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0025_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
