# Generated by Django 2.2.11 on 2020-05-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0028_auto_20200506_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='slug',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='pokemon',
            field=models.ManyToManyField(to='pokemon.Pokemon'),
        ),
    ]
