# Generated by Django 2.2.11 on 2020-05-07 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0029_auto_20200507_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='date_published',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='date_updated',
        ),
    ]
