# Generated by Django 2.2.11 on 2020-05-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0030_auto_20200507_0308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField(max_length=5000)),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
                ('pokemon', models.ManyToManyField(to='pokemon.Pokemon')),
            ],
        ),
    ]
