# Generated by Django 2.2.11 on 2020-05-07 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0031_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
