# Generated by Django 2.2.11 on 2020-05-09 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0032_delete_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='homepage_script',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
